# -*- coding: utf-8 -*-
"""diabetes_prediction_logistic_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fEq6j-eopy7Rj26jbySt-e40o97Zro7n
"""

# Lojistik Regresyon Algoritması

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    confusion_matrix, classification_report, roc_curve, roc_auc_score
)

plt.rcParams['figure.dpi'] = 150

import kagglehub
from kagglehub import KaggleDatasetAdapter

# Dosya ismini belirttik
file_path = "diabetes.csv"

# Veriyi yükle
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "uciml/pima-indians-diabetes-database",
  file_path
)

print("Veri seti boyutu:", df.shape)
print("\nİlk 5 kayıt:\n", df.head())

print(f"Veri seti boyutu: {df.shape[0]} satır, {df.shape[1]} sütun")
print(f"\nSütun isimleri:\n{', '.join(df.columns.tolist())}")

# 'target' yerine 'Outcome' kullandık
print(f"\nSınıf dağılımı (Outcome):")
print(df['Outcome'].value_counts().to_string())

print(f"\nİlk 5 satır:")
display(df.head())

print(f"\nVeri seti istatistikleri:")
display(df.describe())

print(f"\nEksik veri kontrolü:")
print(df.isnull().sum().to_string())

X = df.drop("Outcome", axis=1)
y = df["Outcome"]

print(f"Özellik matrisi (X): {X.shape}")
print(f"Hedef vektör (y):   {y.shape}")
print(f"\nÖzellikler: {X.columns.tolist()}")

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(f"Eğitim seti: {X_train.shape[0]} örnek")
print(f"Test seti:   {X_test.shape[0]} örnek")
print(f"\nEğitim seti sınıf dağılımı:\n{y_train.value_counts().to_string()}")
print(f"\nTest seti sınıf dağılımı:\n{y_test.value_counts().to_string()}")

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Özellikler standardize edildi (mean=0, std=1)")
print(f"\nEğitim seti ilk satır (ölçeklenmiş):")
print(np.round(X_train_scaled[0], 3))

## 7. Lojistik Regresyon Modeli Eğitimi

model = LogisticRegression(
    penalty='l2',
    C=1.0,
    solver='lbfgs',
    max_iter=1000,
    random_state=42,
    class_weight='balanced'  # Bu satırı eklemeniz model başarısını artırır
)

model.fit(X_train_scaled, y_train)
print("Model eğitimi tamamlandı.")

# Model katsayıları
print(f"Kesişim (bias - β₀): {model.intercept_[0]:.4f}")
print(f"\nKatsayılar (β₁ ... βₙ):")
coef_df = pd.DataFrame({
    'Özellik': X.columns,
    'Katsayı': model.coef_[0],
    '|Katsayı|': np.abs(model.coef_[0])
}).sort_values('|Katsayı|', ascending=False)
display(coef_df)

# Özellik önem sıralaması görselleştirmesi
plt.figure(figsize=(10, 6))
colors = ['crimson' if c > 0 else 'royalblue' for c in coef_df['Katsayı']]
plt.barh(coef_df['Özellik'], coef_df['Katsayı'], color=colors)
plt.axvline(0, color='black', linewidth=0.8)
plt.xlabel('Katsayı Değeri')
plt.title('Lojistik Regresyon Katsayıları (Özellik Önem Sırası)')
plt.gca().invert_yaxis()
plt.show()

y_pred = model.predict(X_test_scaled)
y_pred_proba = model.predict_proba(X_test_scaled)[:, 1]

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
auc_roc = roc_auc_score(y_test, y_pred_proba)

print("=== MODEL PERFORMANS METRİKLERİ ===")
print(f"  Doğruluk (Accuracy):     {accuracy:.4f}  ({(accuracy*100):.2f}%)")
print(f"  Hassasiyet (Precision):  {precision:.4f}  ({(precision*100):.2f}%)")
print(f"  Duyarlılık (Recall):     {recall:.4f}  ({(recall*100):.2f}%)")
print(f"  F1-Skoru:                {f1:.4f}")
print(f"  AUC-ROC:                 {auc_roc:.4f}")

# Karmaşıklık Matrisi
cm = confusion_matrix(y_test, y_pred)

print("=== KARIŞIKLIK MATRİSİ (Confusion Matrix) ===")
print(f"               Tahmin: 0 (Sağlıklı)  Tahmin: 1 (Diyabetli)")
print(f"  Gerçek: 0 (Sağlıklı)   {cm[0,0]:3d} (TN)              {cm[0,1]:3d} (FP)")
print(f"  Gerçek: 1 (Diyabetli) {cm[1,0]:3d} (FN)              {cm[1,1]:3d} (TP)")
print()
print("=== SINIFLANDIRMA RAPORU ===")
print(classification_report(y_test, y_pred, target_names=["Sağlıklı", "Diyabetli"]))

# Karmaşıklık Matrisi ve ROC Eğrisi Görselleştirme
fig, ax = plt.subplots(1, 2, figsize=(14, 5))

# Confusion Matrix heatmap (Etiketler güncellendi)
im = ax[0].imshow(cm, cmap='Blues')
ax[0].set_xticks([0, 1])
ax[0].set_yticks([0, 1])
ax[0].set_xticklabels(['Tahmin: Sağlıklı', 'Tahmin: Diyabetli'])
ax[0].set_yticklabels(['Gerçek: Sağlıklı', 'Gerçek: Diyabetli'])

for i in range(2):
    for j in range(2):
        # Etiketleri (TN, FP, FN, TP) ve sayıları yazdırıyoruz
        label = "TN" if i==0 and j==0 else "FP" if i==0 and j==1 else "FN" if i==1 and j==0 else "TP"
        ax[0].text(j, i, f'{cm[i, j]}\n({label})',
                   ha='center', va='center', fontsize=14, fontweight='bold',
                   color='white' if cm[i, j] > cm.max()/2 else 'black')
ax[0].set_title('Confusion Matrix', fontsize=14)

# ROC Curve (y_pred_proba'nın tanımlı olduğundan emin olun)
# Not: Eğer hata alırsanız önce y_pred_proba = model.predict_proba(X_test_scaled)[:, 1] çalıştırın
fpr, tpr, thresholds = roc_curve(y_test, y_pred_proba)
ax[1].plot(fpr, tpr, 'b-', linewidth=2, label=f'ROC (AUC = {auc_roc:.3f})')
ax[1].plot([0, 1], [0, 1], 'r--', linewidth=1, label='Random (AUC = 0.5)')
ax[1].fill_between(fpr, tpr, alpha=0.15, color='blue')
ax[1].set_xlim([0.0, 1.0])
ax[1].set_ylim([0.0, 1.05])
ax[1].set_xlabel('False Positive Rate (1 - Specificity)')
ax[1].set_ylabel('True Positive Rate (Sensitivity)')
ax[1].set_title('ROC Curve', fontsize=14)
ax[1].legend(loc='lower right')
ax[1].grid(alpha=0.3)

plt.tight_layout()
plt.show()

# Örnek tahmin
sample = X_test.iloc[0:1]
sample_scaled = scaler.transform(sample)
sample_proba = model.predict_proba(sample_scaled)[0, 1]
sample_pred = model.predict(sample_scaled)[0]

print("Örnek hasta verisi:")
display(sample)

# Etiketleri güncelledik: 'Diyabetli' ve 'Sağlıklı'
status = 'Diyabetli' if sample_pred == 1 else 'Sağlıklı'
gercek_durum = 'Diyabetli' if y_test.iloc[0] == 1 else 'Sağlıklı'

print(f"\nDiyabet riski (olasılık): {sample_proba:.4f} ({sample_proba*100:.1f}%)")
print(f"Tahmin: {sample_pred} ({status})")
print(f"Gerçek: {y_test.iloc[0]} ({gercek_durum})")

print("=== SONUÇ TABLOSU ===")
print(f"  Doğruluk (Accuracy):     {accuracy:.4f}  ({(accuracy*100):.2f}%)")
print(f"  Hassasiyet (Precision):  {precision:.4f}  ({(precision*100):.2f}%)")
print(f"  Duyarlılık (Recall):     {recall:.4f}  ({(recall*100):.2f}%)")
print(f"  F1-Skoru:                {f1:.4f}")
print(f"  AUC-ROC:                 {auc_roc:.4f}")