# -*- coding: utf-8 -*-
"""temel_python_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wxDM5swA0iN4bOnaQSuSmSfFBxVudw0t

# 🐍 Temel Python Komutları - Alıştırma Defteri 2

Bu defterde Python'un temel konularını farklı sorularla pekiştireceksiniz.

---

## 1️⃣ Değişkenler ve Veri Tipleri
"""

# Örnek: Çoklu atama ve değer değiştirme
x = y = z = 0
print(x, y, z)

a, b, c = 1, 2.5, "Python"
print(a, b, c)

# İki değişkeni yer değiştirme
a, b = b, a
print("Yer değişti:", a, b)

"""### 🔸 Soru 1:
Tek satırda `isim`, `yas`, `maas` değişkenlerine sırasıyla `"Zeynep"`, `32`, `15000.50` değerlerini atayın ve her birini ayrı `print` ile yazdırın.
"""

# Cevabınızı buraya yazın:

"""### 🔸 Soru 2:
Aşağıdaki ifadelerin Python'da geçerli olup olmadığını `try-except` kullanmadan, sadece `type()` ve mantık yürüterek tahmin edin, sonra çalıştırarak doğrulayın:
- `"5" + 5`
- `"5" * 3`
- `True + 1`
- `None == False`
"""

# Tahminlerinizi yorum satırı olarak yazın, sonra çalıştırın:

# "5" + 5    -> Tahminim:
# print("5" + 5)

# "5" * 3    -> Tahminim:
print("5" * 3)

# True + 1   -> Tahminim:
print(True + 1)

# None == False -> Tahminim:
print(None == False)

"""---
## 2️⃣ Operatörler
"""

# Örnek: Mantıksal operatörler
yas = 20
vatandas = True

oy_kullanabilir = yas >= 18 and vatandas
print("Oy kullanabilir:", oy_kullanabilir)

indirim = yas < 18 or yas > 65
print("İndirim hakkı:", indirim)

"""### 🔸 Soru 3:
Bir üçgenin kenar uzunlukları veriliyor. Üçgen eşitsizliği kuralına göre (`a + b > c` vb.) geçerli bir üçgen oluşturup oluşturmadığını tek bir `and` ifadesiyle kontrol edin.
"""

# Cevabınızı buraya yazın:
a, b, c = 3, 4, 5

"""### 🔸 Soru 4:
Atama operatörlerini (`+=`, `-=`, `*=`, `//=`) kullanarak `toplam = 100` değişkenini sırasıyla:
- 25 artırın
- 3 ile çarpın
- 5'e tam bölün
- 10 azaltın

Her adımdan sonra değeri yazdırın.
"""

# Cevabınızı buraya yazın:
toplam = 100

"""---
## 3️⃣ String (Metin) İşlemleri
"""

# Örnek: join ve split
kelimeler = ["elma", "armut", "kiraz"]
metin = ", ".join(kelimeler)
print(metin)

geri = metin.split(", ")
print(geri)

# Sayı formatlama
pi = 3.14159265
print(f"Pi sayısı: {pi:.2f}")
print(f"Para: {15000:,} TL")

"""### 🔸 Soru 5:
Aşağıdaki e-posta adresinden `@` işaretini kullanarak kullanıcı adını ve domain'i ayırın. Sonuçları ayrı değişkenlere atayıp yazdırın.
"""

# Cevabınızı buraya yazın:
email = "kullanici.adi@ornek.com"

"""### 🔸 Soru 6:
Bir palindrom kontrolü yapın: verilen kelimeyi tersine çevirip orijinaliyle karşılaştırın.
- `"kaçak"` → palindrom mu?
- `"python"` → palindrom mu?
"""

# Cevabınızı buraya yazın:
# İpucu: kelime[::-1] ifadesi kelimeyi tersine çevirir
kelime1 = "kaçak"
kelime2 = "python"

"""---
## 4️⃣ Koşullu İfadeler (if / elif / else)
"""

# Örnek: Ternary (tek satır if)
sayi = 7
durum = "tek" if sayi % 2 != 0 else "çift"
print(f"{sayi} sayısı {durum}")

"""### 🔸 Soru 7:
Bir yılın artık yıl olup olmadığını kontrol edin.
Artık yıl kuralı:
- 4'e tam bölünebiliyorsa artık yıldır
- Ama 100'e bölünebiliyorsa artık yıl **değildir**
- Ama 400'e bölünebiliyorsa yine artık yıldır
"""

# Cevabınızı buraya yazın:
# Test: 2000 (artık), 1900 (değil), 2024 (artık), 2023 (değil)
yil = 2024

"""### 🔸 Soru 8:
Bir mağazada indirim hesabı yapın:
- 500 TL altı → indirim yok
- 500-1000 TL arası → %10 indirim
- 1000-2000 TL arası → %20 indirim
- 2000 TL üstü → %30 indirim

Ödenmesi gereken tutarı yazdırın.
"""

# Cevabınızı buraya yazın:
fiyat = 1500

"""---
## 5️⃣ Döngüler (for / while)
"""

# Örnek: enumerate ve zip
renkler = ["kırmızı", "yeşil", "mavi"]

for i, renk in enumerate(renkler, start=1):
    print(f"{i}. {renk}")

print("---")

isimler = ["Ali", "Ayşe", "Can"]
notlar = [85, 92, 78]

for isim, not_ in zip(isimler, notlar):
    print(f"{isim}: {not_}")

"""### 🔸 Soru 9:
`break` ve `continue` kullanımını gösterin:
- 1-20 arasında döngü kurun
- 3'ün katlarını `continue` ile atlayın
- 15'e ulaşınca `break` ile çıkın
- Yazdırılan sayıları gösterin
"""

# Cevabınızı buraya yazın:

"""### 🔸 Soru 10:
`while` döngüsü ile basamak sayısı bulma: Verilen bir sayının kaç basamaklı olduğunu, sayıyı 10'a bölerek bulun (string dönüşümü kullanmadan).
"""

# Cevabınızı buraya yazın:
# Örnek: 4752 -> 4 basamaklı
sayi = 4752

"""### 🔸 Soru 11:
`enumerate` kullanarak bir alışveriş listesini numaralandırıp yazdırın, ardından toplam ürün sayısını gösterin.
"""

# Cevabınızı buraya yazın:
alisveris = ["ekmek", "süt", "yumurta", "peynir", "domates"]

"""---
## 6️⃣ Listeler ve Demetler (Tuple)
"""

# Örnek: Tuple
koordinat = (41.0082, 28.9784)  # İstanbul koordinatları
enlem, boylam = koordinat       # Unpacking
print(f"Enlem: {enlem}, Boylam: {boylam}")

# Tuple değiştirilemez!
# koordinat[0] = 40  # -> TypeError!

"""### 🔸 Soru 12:
Bir öğrenci listesi var. Her öğrenci `(isim, not)` tuple'ı olarak saklanıyor.
- Notu 70'in üzerinde olanları filtreleyin
- En yüksek notu alan öğrenciyi bulun
- Notların ortalamasını hesaplayın
"""

# Cevabınızı buraya yazın:
ogrenciler = [
    ("Ahmet", 85),
    ("Büşra", 62),
    ("Can", 91),
    ("Deniz", 74),
    ("Elif", 58),
    ("Furkan", 88)
]

"""### 🔸 Soru 13 (Set):
İki sınıfın öğrenci listesi var. `set` kullanarak:
- Her iki sınıfta da bulunan öğrencileri bulun (kesişim)
- Toplam kaç farklı öğrenci olduğunu bulun (birleşim)
- Sadece A sınıfında olup B'de olmayan öğrencileri bulun (fark)
"""

# Cevabınızı buraya yazın:
sinif_a = {"Ali", "Ayşe", "Can", "Dilan", "Ece"}
sinif_b = {"Can", "Dilan", "Fatih", "Gökçe", "Hakan"}

"""---
## 7️⃣ Sözlükler (Dictionary)
"""

# Örnek: Dict comprehension
kareler = {x: x**2 for x in range(1, 6)}
print(kareler)

# Filtrelemeli
cift_kareler = {x: x**2 for x in range(1, 11) if x % 2 == 0}
print(cift_kareler)

"""### 🔸 Soru 14:
Bir cümledeki her harfin kaç kez geçtiğini sayan bir sözlük oluşturun (boşlukları saymayin, büyük/küçük harf farkı olmasın).
"""

# Cevabınızı buraya yazın:
cumle = "merhaba dünya"

"""---
## 8️⃣ Fonksiyonlar
"""

# Örnek: *args ve **kwargs
def toplam(*sayilar):
    return sum(sayilar)

print(toplam(1, 2, 3))
print(toplam(10, 20, 30, 40, 50))

def kullanici_bilgi(**bilgiler):
    for anahtar, deger in bilgiler.items():
        print(f"{anahtar}: {deger}")

kullanici_bilgi(ad="Selin", yas=25, sehir="İzmir")

"""### 🔸 Soru 15:
Özyinelemeli (recursive) bir fonksiyon yazın: `faktoriyel(n)` - n! hesaplasın.
- 0! = 1
- n! = n × (n-1)!

5!, 10! değerlerini hesaplayın.
"""

# Cevabınızı buraya yazın:
def faktoriyel(n):
    pass

"""### 🔸 Soru 16:
`lambda` fonksiyonu kullanarak:
- Bir sayının karesini hesaplayan lambda
- İki sayının büyüğünü döndüren lambda
- `sorted()` ile bir isim listesini son harfe göre sıralayan lambda
"""

# Cevabınızı buraya yazın:
isimler = ["Zeynep", "Ali", "Mahmut", "Su", "Berk"]

"""---
## 9️⃣ Dosya İşlemleri
"""

# Örnek: Dosya yazma ve okuma
with open("ornek.txt", "w", encoding="utf-8") as dosya:
    dosya.write("Merhaba!\n")
    dosya.write("Bu bir test dosyasıdır.\n")

with open("ornek.txt", "r", encoding="utf-8") as dosya:
    icerik = dosya.read()
    print(icerik)

"""### 🔸 Soru 17:
Bir alışveriş listesini `alisveris.txt` dosyasına yazın (her ürün ayrı satırda). Sonra dosyayı okuyarak ürünleri numaralı şekilde ekrana yazdırın.
"""

# Cevabınızı buraya yazın:
urunler = ["ekmek", "süt", "yumurta", "peynir", "zeytin"]

"""---
## 🔟 Bonus: Kapsamlı Uygulama

### 🔸 Soru 18 (Bütünleştirici):
Basit bir **öğrenci not sistemi** yazın:

- `ogrenciler` adında boş bir sözlük oluşturun (anahtar: isim, değer: notlar listesi)
- `ogrenci_ekle(isim)`: Yeni öğrenci ekler
- `not_ekle(isim, not_)`: Öğrenciye not ekler. Öğrenci yoksa hata mesajı verir.
- `ortalama_hesapla(isim)`: Öğrencinin not ortalamasını döndürür
- `sinif_raporu()`: Tüm öğrencileri ve ortalamalarını yazdırır, sınıf ortalamasını gösterir

En az 3 öğrenci ve her birine 3 not girerek test edin.
"""

# Cevabınızı buraya yazın:
ogrenciler = {}

def ogrenci_ekle(isim):
    pass

def not_ekle(isim, not_):
    pass

def ortalama_hesapla(isim):
    pass

def sinif_raporu():
    pass

# Test kodu:
# ogrenci_ekle("Ahmet")
# ogrenci_ekle("Büşra")
# ogrenci_ekle("Can")
# not_ekle("Ahmet", 85)
# not_ekle("Ahmet", 90)
# not_ekle("Ahmet", 78)
# not_ekle("Büşra", 92)
# not_ekle("Büşra", 88)
# not_ekle("Büşra", 95)
# not_ekle("Can", 70)
# not_ekle("Can", 65)
# not_ekle("Can", 73)
# sinif_raporu()

"""---
## 📊 Özet Çizelgesi

| Konu | Sorular | Tamamlandı mı? |
|------|---------|----------------|
| Değişkenler & Tipler | 1, 2 | ☐ |
| Operatörler | 3, 4 | ☐ |
| String İşlemleri | 5, 6 | ☐ |
| Koşullar | 7, 8 | ☐ |
| Döngüler | 9, 10, 11 | ☐ |
| Liste, Tuple, Set | 12, 13 | ☐ |
| Sözlükler | 14 | ☐ |
| Fonksiyonlar | 15, 16 | ☐ |
| Dosya İşlemleri | 17 | ☐ |
| Bütünleştirici | 18 | ☐ |

> 💡 **İpucu:** Takıldığınız yerde `help()` fonksiyonunu veya Python dokümantasyonunu kullanın!
"""