# -*- coding: utf-8 -*-
"""Python 1 Ders.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sdGgeJCWAaFGsbAFCgTgdw18W-j_K4cR

## veri tipleri

int

float

string

bool
"""

sayi=24
print(type(sayi))

pi=3.14
print(type(pi))

araba ="İ20N"
print(type(araba))

sıfır=True
ikinci_el= False
print(type(sıfır))
print(type(ikinci_el))

a= 450
b= 350
c=a+b
c

toplam =a+b
print(toplam)

a,b = 10,3
print(a+b) # toplama
print(a-b) #çıkarma
print(a*b) # çarpma
print(a/b) # bölme
print(a//b) # tam bölme
print(a%b) #kalan
print(a**b)# üs alma

a,b = 10,3
print(a==b) #eşit mi ?
print(a!=b) #eşit değil mi ?
print(a>b)  #büyük mü ?
print(a<b)  #küçük mü ?
print(a>=b) #büyük eşit mi ?
print(a<=b) #küçük eşit mi ?

x,y = True, False
print(x and y) # ve
print(x or y)  # veya
print(not x)   #Değil

n=10
n+=5 # n+5
n-=3 # n-3
n*=2 # n*2
n/=4 #n/4
n//=2
n**=3
n%=5

"""### String işlemleri"""

s= "Softito"
print(s.upper())
print(s.lower())
print(s.title())
print(s.capitalize())
print(s.swapcase())
print(s.replace("t","$"))
print(s.split("f"))
print(len(s))
print(s[0:5])
print("la"in s)

"""#### Liste İşlemleri"""

liste = [70,78,16,53,42,28]

liste.append(24)
liste.insert(2,24)
liste.pop()
liste.sort()
liste.reverse()
liste.count(24)
liste.index(24)
print(sum(liste))
print(max(liste))
print(min(liste))

liste

"""## Matematik İşlemler"""

import math
print(math.sqrt(16))
print(math.pow(2,3))
print(math.pi)
print(math.factorial)
print(math.floor(3.9))
print(math.ceil(3.1))
print(math.log10(1000))
print(math.fabs(-10))

"""### Tip dönüşümleri"""

print(int("42"))
print(float("3.14"))
print(str(100))
print(bool(1))
print(bool(0))

yas = 18
if yas >= 18:
  print("yetişkin")
elif yas >= 13:
  print("genç")
else:
  print("çoçuk")

sepet_tutarı=1320

if sepet_tutarı >=2000:
  print("tebrikler indirim kazandınız")
  ödenecek_tutar=sepet_tutarı-200
  print("ödemeniz gereken tutar",ödenecek_tutar)
else:
  print("2000 tl altına indirim uygulanmaz çünkü siz fakirsiniz")
  ödenecek_tutar=sepet_tutarı
  print("ödemeniz gereken tutar",ödenecek_tutar)
#

for i in range (5):

  print(i)
x=0

while x<3:
  print(x)
  x+=1

"""Listeler"""

meyveler = ["elma","armut","muz","karpuz"]
meyveler.insert(3,"kavun")
print(meyveler[0]) # index e göre elemanı yazdırır
print(len(meyveler)) # boyutu verir
meyveler.append("çilek") # eleman ekleme
meyveler.remove("armut") # eleman silme
meyveler.pop() # son elemanı silme

meyveler

"""## Sözlükler"""

kisi={
    "ad":"Berkay",
    "yas":23,
    "sehir":"İstanbul",
    "meslek":"Yazılım Geliştirici"
}

print(kisi["ad"])
print(kisi["yas"])
print(kisi["sehir"])
print(kisi["meslek"])

"""## Fonksiyonlar"""

def selamla(): # selamla  ile etiket
  print("merhaba dünya")  # fonksiyonlar belirli bir işi yapan kod parçlarını içeren kutular

selamla()

def kisiye_ozel_kampanya(musteri_numarasi):# parametre ()
  print(f"{musteri_numarasi} numaralı müşteimiz iphone 15 hediyesi ,almak için linke tıkla")

kisiye_ozel_kampanya(123456789)

def topla(a,b):
  return a+b # sonucu bize teslim
toplam=topla(10,20)
print(toplam)

def selam_ver(isim="Ziyaretçi"):
  print(f"merhaba {isim}")


selam_ver()

selam_ver("Tuna")

def tek_mi_cift_mi(sayi):
  if sayi%2==0:
    return "Çift"
  else:
    return  "Tek"
print(tek_mi_cift_mi(10))

def pozitifleri_sec(liste):
  yeni_liste = []
  for sayi in liste:
    if sayi>0:
      yeni_liste.append(sayi)
  return yeni_liste

sayilar=[-12,10,0,-2,-3,8]
print(pozitifleri_sec(sayilar))

def dikdortgen(kisa_kenar,uzun_kenar):
  alan=kisa_kenar*uzun_kenar
  cevre = 2*(kisa_kenar+uzun_kenar)
  return alan , cevre

a,c =dikdortgen(3,4)
print(a,c)

def indirimli_fiyat(tutar):
  if tutar >= 1000:
    return tutar*0.80
  elif tutar >=500:
    return tutar*0.90
  else:
    return tutar

print(indirimli_fiyat(1200))
print(indirimli_fiyat(800))
print(indirimli_fiyat(400))

"""Class(Sınıf)"""

class Araba:
  def __init__(self,marka,model,yil):
    self.marka=marka
    self.model=model
    self.yil=yil

araba1= Araba("Ford","Shelby",1969)
araba2=Araba("Tesla","Model S",2023)

print(araba1.marka)
print(araba1.model)
print(araba1.yil)

x= 5 #int
x =" Araba" # str

class Dikdortgen:
    def __init__(self, en, boy):
        self.en  = en
        self.boy = boy

    def alan(self):
        return self.en * self.boy

    def cevre(self):
        return 2 * (self.en + self.boy)

    def bilgi(self):
        print(f"Alan: {self.alan()}, Çevre: {self.cevre()}")

d = Dikdortgen(5, 3)
d.bilgi()
print(d.alan())    # 15
print(d.cevre())   # 16

# Bunların her biri ayrı bir instance:
d1 = Dikdortgen(5, 3)    # 1. instance
d2 = Dikdortgen(10, 7)   # 2. instance
d3 = Dikdortgen(2, 2)    # 3. instance
print(d1.en)
print(d2.en)
print(d3.en)

d1.alan()
d2.alan()
d3.alan()

class Hayvan:
    def __init__(self, isim, yas):
        self.isim = isim
        self.yas  = yas

    def ses_cikar(self):
        return "..."

    def tanitim(self):
        print(f"{self.isim} ({self.yas} yaş): {self.ses_cikar()}")


class Kopek(Hayvan):   # Hayvan'dan türüyor
    def __init__(self, isim, yas, irk):
        super().__init__(isim, yas)
        self.irk = irk

    def ses_cikar(self):   # override
        return "Hav hav!"


class Kedi(Hayvan):
    def ses_cikar(self):
        return "Miyav!"


k = Kopek("Karabaş", 3, "Kangal")
c = Kedi("Pamuk", 5)

k.tanitim()
c.tanitim()

class BankaHesabi:
    def __init__(self, sahip, bakiye=0):
        self.sahip   = sahip
        self._bakiye = bakiye   # dahili

    @property
    def bakiye(self):
        return self._bakiye

    @bakiye.setter
    def bakiye(self, miktar):
        if miktar < 0:
            raise ValueError("Bakiye negatif olamaz!")
        self._bakiye = miktar

    def para_yatir(self, miktar):
        self._bakiye += miktar
        print(f"+{miktar} TL → Bakiye: {self._bakiye} TL")

    def para_cek(self, miktar):
        if miktar > self._bakiye:
            print("Yetersiz bakiye!")
        else:
            self._bakiye -= miktar
            print(f"-{miktar} TL → Bakiye: {self._bakiye} TL")

h = BankaHesabi("Ali", 1000)
h.para_yatir(500)
h.para_cek(200)
h.para_cek(2000)

class Vektor:
    def __init__(self, x, y):
        self.x = x
        self.y = y

    def __str__(self):        # print() için
        return f"({self.x}, {self.y})"

    def __repr__(self):       # geliştirici çıktısı
        return f"Vektor({self.x}, {self.y})"

    def __add__(self, other):  # + operatörü
        return Vektor(self.x + other.x, self.y + other.y)

    def __len__(self):         # len() için (boyut sayısı)
        return 2

    def uzunluk(self):
        return (self.x**2 + self.y**2) ** 0.5

v1 = Vektor(3, 4)
v2 = Vektor(1, 2)

print(v1)           # __str__
print(v1 + v2)      # __add__
print(len(v1))      # __len__
print(v1.uzunluk()) # 5.0

print(t)
repr(t)

class Tarih:
    def __init__(self, gun, ay, yil):
        self.gun = gun
        self.ay  = ay
        self.yil = yil

    def __str__(self):
        # kullanıcı dostu — güzel görünsün
        return f"{self.gun} {self.ay} {self.yil}"

    def __repr__(self):
        # geliştirici dostu — nesneyi yeniden yaratabileyim
        return f"Tarih({self.gun}, {self.ay}, {self.yil})"


t = Tarih(15, 6, 2024)

class Ogrenci:
    okul = "Atatürk Lisesi"    #hiçbir nesne yok şuan sadece ne var sınıfımız var
    kayitli_sayi = 0         # ben sınıfa dair özellikler ekleyeceğim yer tutuyor


    def __init__(self, ad, not_): # nesneye ait herşeyi burda yazarız
        self.ad   = ad
        self.not_ = not_
        Ogrenci.kayitli_sayi += 1

    def bilgi(self):
        print(f"{self.ad} | {self.okul} | Not: {self.not_}")


o1 = Ogrenci("Ayşe", 95)
o2 = Ogrenci("Mehmet", 78) # nesneler

o1.bilgi()
o2.bilgi()
print("Toplam öğrenci:", Ogrenci.kayitli_sayi)

# Class değişkeni tüm örnekleri etkiler
Ogrenci.okul = "Cumhuriyet Lisesi"
o1.bilgi()   # okul değişti!
o2.bilgi()

