# -*- coding: utf-8 -*-
"""python_class_sorular.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yfQYRfewhHSDHxhGfVVTeGK1_44Q_WOQ

# Python Class — Kolaydan Zora Sorular
Her soruyu çözdükten sonra alttaki test hücresini çalıştırarak cevabını kontrol edebilirsin.

---
## 🟢 KOLAY

### Soru 1 — Temel class
Aşağıdaki özelliklere sahip bir `Kisi` class'ı yaz:
- `ad`, `soyad`, `yas` instance değişkenleri olsun
- `tanitim()` metodu `"Merhaba, ben Ali Veli, 25 yaşındayım."` formatında yazdırsın
"""

# Cevabını buraya yaz
class Kisi:
    def __init__(self, ad, soyad, yas):
      self.ad = ad
      self.soyad = soyad
      self.yas = yas

    def tanitim(self):
      print(f"Merhaba, ben  {self.ad} {self.soyad}, {self.yas} yaşındayım.")

# TEST
k = Kisi("Ali", "Veli", 25)
assert k.ad == "Ali"
assert k.soyad == "Veli"
assert k.yas == 25
k.tanitim()  # Merhaba, ben Ali Veli, 25 yaşındayım.
print("✅ Soru 1 doğru!")

"""---
### Soru 2 — Metotlar
Bir `Dikdortgen` class'ı yaz:
- `en` ve `boy` alsın
- `alan()` → en × boy döndürsün
- `cevre()` → 2 × (en + boy) döndürsün
- `kare_mi()` → en == boy ise `True` döndürsün
"""

# Cevabını buraya yaz
class Dikdortgen:
    def __init__(self, en, boy):
      self.en = en
      self.boy = boy
    def alan(self):
      return self.en * self.boy

    def cevre(self):
      return 2 * (self.en + self.boy)

    def kare_mi(self):
      return self.en == self.boy

# TEST
d1 = Dikdortgen(5, 3)
d2 = Dikdortgen(4, 4)
assert d1.alan() == 15
assert d1.cevre() == 16
assert d1.kare_mi() == False
assert d2.kare_mi() == True
print("✅ Soru 2 doğru!")

"""---
### Soru 3 — `__str__` ve `__repr__`
Bir `Kitap` class'ı yaz:
- `ad` ve `yazar` alsın
- `__str__`  → `"Suç ve Ceza — Dostoyevski"` formatında döndürsün
- `__repr__` → `"Kitap('Suç ve Ceza', 'Dostoyevski')"` formatında döndürsün
"""

# Cevabını buraya yaz
class Kitap:
    def __init__(self, ad, yazar):
      self.ad = ad
      self.yazar = yazar
    def __str__(self):
      return f"{self.ad} — {self.yazar}"

    def __repr__(self):
      return f"Kitap('{self.ad}', '{self.yazar}')"

# TEST
k = Kitap("Suç ve Ceza", "Dostoyevski")
assert str(k) == "Suç ve Ceza — Dostoyevski"
assert repr(k) == "Kitap('Suç ve Ceza', 'Dostoyevski')"
print("✅ Soru 3 doğru!")

"""---
### Soru 4 — Class değişkeni
Bir `Araba` class'ı yaz:
- `marka` instance değişkeni olsun
- `tekerlek_sayisi = 4` class değişkeni olsun (tüm arabalar için sabit)
- `toplam_araba` class değişkeni her yeni nesne oluşturulduğunda 1 artsın
"""

# Cevabını buraya yaz
class Araba:
    toplam_araba = 0
    tekerlek_sayisi = 4

    def __init__(self, marka):
        self.marka = marka
        Araba.toplam_araba += 1


a1 = Araba("Toyota")
print(f"1.Araba: {a1.marka}, Tekerlek: {a1.tekerlek_sayisi}")
print(f"Toplam Araba Sayısı: {Araba.toplam_araba}")

a2 = Araba("BMW")
print(f"2.Araba: {a2.marka}, Tekerlek: {a2.tekerlek_sayisi}")
print(f"Toplam Araba Sayısı: {Araba.toplam_araba}")

# TEST
Araba.toplam_araba = 0  # sıfırla
a1 = Araba("BMW")
a2 = Araba("Toyota")
a3 = Araba("Ford")
assert Araba.tekerlek_sayisi == 4
assert Araba.toplam_araba == 3
assert a1.marka == "BMW"
print("✅ Soru 4 doğru!")

"""---
## 🟡 ORTA

### Soru 5 — Kalıtım
`Hayvan` class'ından türeyen `Kopek` ve `Kedi` class'ları yaz:
- `Hayvan`: `isim` alsın, `ses_cikar()` → `"..."` döndürsün
- `Kopek`: `ses_cikar()` → `"Hav!"` döndürsün, `getir()` → `"[isim] topu getirdi!"` yazdırsın
- `Kedi`: `ses_cikar()` → `"Miyav!"` döndürsün
"""

# Cevabını buraya yaz
class Hayvan:
    def __init__(self, isim):
      self.isim = isim

    def ses_cikar(self):
      return "..."

class Kopek(Hayvan):
    def ses_cikar(self):
       return "Hav!"

    def getir(self):
        print(f"{self.isim} topu getirdi!")

class Kedi(Hayvan):
    def ses_cikar(self):
        return "Miyav!"

# TEST
k = Kopek("Karabaş")
c = Kedi("Pamuk")
assert k.isim == "Karabaş"
assert k.ses_cikar() == "Hav!"
assert c.ses_cikar() == "Miyav!"
assert isinstance(k, Hayvan)
assert isinstance(c, Hayvan)
k.getir()  # Karabaş topu getirdi!
print("✅ Soru 5 doğru!")

"""---
### Soru 6 — Kapsülleme ve @property
Bir `Sicaklik` class'ı yaz:
- `_derece` ile saklansın
- `@property` ile `derece` okunabilsin
- `@derece.setter` ile atanabilsin ama `-273`'ün altına düşürülemesin (mutlak sıfır), düşürülmeye çalışılınca `ValueError` fırlatsın
- `@property` ile `fahrenheit` hesaplansın → `(derece × 9/5) + 32`
"""

# Cevabını buraya yaz
class Sicaklik:
    def __init__(self, derece):
        self._derece = derece

    @property
    def derece(self):
        return self._derece

    @derece.setter
    def derece(self, yeni_deger):
        if yeni_deger < -273:
            raise ValueError("Sıcaklık mutlak sıfırın altına düşemez!")
        self._derece = yeni_deger

    @property
    def fahrenheit(self):
        return (self._derece * 9/5) + 32

# TEST
s = Sicaklik(100)
assert s.derece == 100
assert s.fahrenheit == 212.0
s.derece = 0
assert s.fahrenheit == 32.0
try:
    s.derece = -300
    assert False, "ValueError bekleniyor"
except ValueError:
    pass
print("✅ Soru 6 doğru!")

"""---
### Soru 7 — Dunder metotlar
Bir `Para` class'ı yaz:
- `miktar` ve `para_birimi` alsın (varsayılan: `"TL"`)
- `__str__`  → `"100 TL"` formatında
- `__add__`  → iki Para toplanabilsin (aynı para birimi kontrolü yap, farklıysa `ValueError`)
- `__eq__`   → miktar ve para birimi eşitse `True`
- `__lt__`   → miktar karşılaştırması
"""

# Cevabını buraya yaz
class Para:
    def __init__(self, miktar, para_birimi="TL"):
        self.miktar = miktar
        self.para_birimi = para_birimi

    def __str__(self):
        return f"{self.miktar} {self.para_birimi}"

    def __add__(self, diger):
        if self.para_birimi != diger.para_birimi:
            raise ValueError("Farklı para birimleri toplanamaz!")
        return Para(self.miktar + diger.miktar, self.para_birimi)

    def __eq__(self, diger):
        return self.miktar == diger.miktar and self.para_birimi == diger.para_birimi

    def __lt__(self, diger):
        if self.para_birimi != diger.para_birimi:
             raise ValueError("Farklı birimler karşılaştırılamaz!")
        return self.miktar < diger.miktar

# TEST
p1 = Para(100, "TL")
p2 = Para(50, "TL")
p3 = Para(100, "TL")
p4 = Para(50, "USD")
assert str(p1) == "100 TL"
assert (p1 + p2).miktar == 150
assert p1 == p3
assert p2 < p1
try:
    p1 + p4
    assert False, "ValueError bekleniyor"
except ValueError:
    pass
print("✅ Soru 7 doğru!")

"""---
### Soru 8 — @classmethod ve @staticmethod
Bir `Dikdortgen` class'ı yaz:
- `en` ve `boy` alsın
- `@classmethod kare_olustur(cls, kenar)` → kare döndürsün (en == boy == kenar)
- `@staticmethod gecerli_mi(en, boy)` → ikisi de 0'dan büyükse `True` döndürsün
"""

# Cevabını buraya yaz
class Dikdortgen:
    def __init__(self, en, boy):
        self.en = en
        self.boy = boy

    @classmethod
    def kare_olustur(cls, kenar):
        return cls(kenar, kenar)

    @staticmethod
    def gecerli_mi(en, boy):
        return en > 0 and boy > 0

# TEST
d = Dikdortgen(5, 3)
kare = Dikdortgen.kare_olustur(4)
assert kare.en == 4
assert kare.boy == 4
assert Dikdortgen.gecerli_mi(5, 3) == True
assert Dikdortgen.gecerli_mi(-1, 3) == False
assert Dikdortgen.gecerli_mi(0, 3) == False
print("✅ Soru 8 doğru!")

"""---
## 🔴 ZOR

### Soru 9 — Iterator class
Bir `AralıkIterator` class'ı yaz:
- `baslangic`, `bitis`, `adim` alsın
- `for` döngüsünde kullanılabilsin
- Python'un `range()` gibi çalışsın ama class olarak
- `__len__` da ekle — kaç eleman üreteceğini döndürsün
"""

# Cevabını buraya yaz
class AralikIterator:
    def __init__(self, baslangic, bitis, adim):
        self.baslangic = baslangic
        self.bitis = bitis
        self.adim = adim

    def __iter__(self):
        self.mevcut = self.baslangic
        return self

    def __next__(self):
        if (self.adim > 0 and self.mevcut >= self.bitis) or \
           (self.adim < 0 and self.mevcut <= self.bitis):
            raise StopIteration
        deger = self.mevcut
        self.mevcut += self.adim
        return deger

    def __len__(self):
        return max(0, (self.bitis - self.baslangic + self.adim - (1 if self.adim > 0 else -1)) // self.adim)

# TEST
a = AralikIterator(0, 10, 2)
assert list(a) == [0, 2, 4, 6, 8]
assert len(a) == 5
b = AralikIterator(1, 6, 1)
assert list(b) == [1, 2, 3, 4, 5]
# iki kez kullanılabilmeli
assert list(a) == [0, 2, 4, 6, 8]
print("✅ Soru 9 doğru!")

"""---
### Soru 10 — Mixin
Aşağıdaki iki Mixin'i yaz ve `Calisan` class'ına ekle:
- `KarsilastirmaMixin`: `__eq__` ve `__lt__` eklesin — karşılaştırma `maas` değerine göre yapılsın
- `YazdirmaMixin`: `yazdir()` metodu tüm instance değişkenlerini `anahtar: değer` formatında yazdırsın
- `Calisan`: `isim`, `departman`, `maas` alsın
"""

# Cevabını buraya yaz
class KarsilastirmaMixin:
    def __eq__(self, diger):
        return self.maas == diger.maas
    def __lt__(self, diger):
        return self.maas < diger.maas
    def __gt__(self, diger):
        return self.maas > diger.maas

class YazdirMixin:
    def yazdir(self):
        for anahtar, deger in self.__dict__.items():
            print(f"{anahtar}: {deger}")

class Calisan(KarsilastirmaMixin, YazdirMixin):
    def __init__(self, isim, departman, maas):
        self.isim = isim
        self.departman = departman
        self.maas = maas

# TEST
c1 = Calisan("Ali", "Yazılım", 50000)
c2 = Calisan("Ayşe", "Tasarım", 60000)
c3 = Calisan("Ali", "Yazılım", 50000)
assert c1 < c2
assert c2 > c1
assert c1 == c3
c1.yazdir()
# isim: Ali
# departman: Yazılım
# maas: 50000
print("✅ Soru 10 doğru!")

"""---
### Soru 11 — Hepsini Birleştir (Proje)
Bir `Kutuphane` sistemi yaz:

**`Kitap` class'ı:**
- `isbn`, `ad`, `yazar`, `mevcut` (varsayılan `True`) alsın
- `__str__` → `"[ISBN] Ad — Yazar"`
- `__repr__` → `"Kitap(isbn, ad, yazar)"`

**`Kutuphane` class'ı:**
- `kitaplar` listesi tut
- `kitap_ekle(kitap)` → listeye ekle
- `__len__` → toplam kitap sayısı
- `__contains__` → ISBN ile kitap var mı kontrolü (`"978..." in kutuphane`)
- `kitap_bul(isbn)` → ISBN ile kitap döndür, bulamazsa `None`
- `odunc_al(isbn)` → kitabı `mevcut=False` yap, zaten alınmışsa hata ver
- `iade_et(isbn)` → kitabı `mevcut=True` yap
- `mevcut_kitaplar()` → sadece mevcut kitapları listele
"""

# Cevabını buraya yaz
class Kitap:
    def __init__(self, isbn, ad, yazar, mevcut=True):
      self.isbn = isbn
      self.ad = ad
      self.yazar = yazar
      self.mevcut = mevcut

    def __str__(self):
        return f"[{self.isbn}] {self.ad} - {self.yazar}"

    def __repr__(self):
        return f"Kitap('{self.isbn}', '{self.ad}', '{self.yazar}')"

class Kutuphane:
    def __init__(self):
        self.kitaplar = []

    def kitap_ekle(self, kitap):
        self.kitaplar.append(kitap)

    def __len__(self):
        return len(self.kitaplar)

    def __contains__(self, isbn):
        return any(k.isbn == isbn for k in self.kitaplar)

    def kitap_bul(self, isbn):
        for k in self.kitaplar:
            if k.isbn == isbn: return k
        return None

    def odunc_al(self, isbn):
        kitap = self.kitap_bul(isbn)
        if kitap and kitap.mevcut:
            kitap.mevcut = False
        else:
            raise Exception("Kitap mevcut değil veya zaten ödünç alınmış.")

    def iade_et(self, isbn):
        kitap = self.kitap_bul(isbn)
        if kitap:
            kitap.mevcut = True

    def mevcut_kitaplar(self):
        return [k for k in self.kitaplar if k.mevcut]

# TEST
k1 = Kitap("978-1", "Suç ve Ceza", "Dostoyevski")
k2 = Kitap("978-2", "1984", "Orwell")
k3 = Kitap("978-3", "Dune", "Herbert")

kutuphane = Kutuphane()
kutuphane.kitap_ekle(k1)
kutuphane.kitap_ekle(k2)
kutuphane.kitap_ekle(k3)

assert len(kutuphane) == 3
assert "978-1" in kutuphane
assert "978-9" not in kutuphane

kutuphane.odunc_al("978-1")
assert k1.mevcut == False
assert len(kutuphane.mevcut_kitaplar()) == 2

kutuphane.iade_et("978-1")
assert k1.mevcut == True

try:
    kutuphane.odunc_al("978-1")
    kutuphane.odunc_al("978-1")  # zaten alınmış
    assert False
except Exception:
    pass

print("✅ Soru 11 doğru! Tebrikler!")