# -*- coding: utf-8 -*-
"""temel_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ofTNvLngZSNPA4xc5XqIS0P_WG29xjUa

# 🐍 Temel Python Komutları - Alıştırma Defteri

Bu defterde Python'un temel konularını öğrenecek ve pratik sorularla kendinizi geliştireceksiniz.

---

## 1️⃣ Değişkenler ve Veri Tipleri
"""



"""### 🔸 Soru 1:
Aşağıdaki değişkenleri tanımlayın ve her birinin tipini `type()` fonksiyonu ile yazdırın:
- `sehir`: "Ankara" (string)
- `nüfus`: 5700000 (integer)
- `sicaklik`: 23.5 (float)
- `yagmur_yagıyor`: False (boolean)
"""



# Cevabınızı buraya yazın:

sehir = "Ankara"
nufus = 5700000
sicaklik = 23.5
yagmur_yagiyor = False

print(type(sehir))
print(type(nufus))
print(type(sicaklik))
print(type(yagmur_yagiyor))

"""### 🔸 Soru 2:
Bir değişkeni `int`'ten `float`'a, `float`'tan `str`'e dönüştürün ve sonuçları yazdırın.

Örnek: `sayi = 42` → `float(sayi)` → `str(float(sayi))`
"""

# Cevabınızı buraya yazın:

sayi = 8

# int'ten float'a
sayi_float = float(sayi)
print(sayi_float)

# float'tan str'e
sayi_str = str(sayi_float)
print(sayi_str)

"""---
## 2️⃣ Operatörler
"""

# Örnek: Aritmetik operatörler
a = 10
b = 3

"""### 🔸 Soru 3:
Kullanıcıdan alınan iki sayı olduğunu varsayın: `x = 17`, `y = 5`
- Toplamlarını, farklarını ve çarpımlarını yazdırın.
- 17'nin 5'e bölümünden kalanı yazdırın.
- 2'nin 8. kuvvetini hesaplayın.
"""

# Cevabınızı buraya yazın:
x = 17
y = 5

# 1. Toplam, fark ve çarpım
print(f"Toplam: {x + y}")    # 22
print(f"Fark: {x - y}")      # 12
print(f"Çarpım: {x * y}")    # 85

# 2. Bölümden kalan (Modülüs)
print(f"Kalan: {x % y}")     # 2

# 3. Kuvvet hesaplama (Üs alma)
print(f"2'nin 8. kuvveti: {2 ** 8}") # 256

"""### 🔸 Soru 4:
Karşılaştırma operatörlerini kullanarak aşağıdaki ifadelerin sonuçlarını (True/False) yazdırın:
- 10 > 5
- 3 == 3.0
- "elma" != "armut"
- 7 <= 7
"""

# Cevabınızı buraya yazın:
print(10 > 5)            # True (10, 5'ten büyüktür)
print(3 == 3.0)          # True (Değerler eşittir, float/int fark etmez)
print("elma" != "armut") # True ("elma", "armut"a eşit değildir)
print(7 <= 7)            # True (7, 7'den küçük değildir ama eşittir)

"""---
## 3️⃣ String (Metin) İşlemleri
"""

# Örnek: String metodları
metin = "Merhaba Python!"

print(metin.upper())       # Büyük harf
print(metin.lower())       # Küçük harf
print(metin.replace("Python", "Dünya"))  # Değiştirme
print(len(metin))          # Uzunluk
print(metin[0:7])          # Dilimleme

"""### 🔸 Soru 5:
`cumle = "  python programlama dili çok güçlüdür  "` değişkeni için:
- Baştaki ve sondaki boşlukları temizleyin (`.strip()`)
- İlk harfini büyük yapın (`.capitalize()`)
- Kaç kelimeden oluştuğunu bulun (`.split()` ve `len()` kullanın)
- "güçlü" kelimesinin cümlede olup olmadığını kontrol edin (`in` operatörü)
"""

# Cevabınızı buraya yazın:

cumle = " python programlama dili çok güçlüdür "

# 1. Boşlukları temizle
temiz_cumle = cumle.strip()

# 2. İlk harfi büyük yap
print(temiz_cumle.capitalize())

# 3. Kelime sayısını bul
kelime_sayisi = len(temiz_cumle.split())
print(f"Kelime sayısı: {kelime_sayisi}")

# 4. "güçlü" kelimesini kontrol et
print("güçlü" in temiz_cumle)

"""### 🔸 Soru 6 (f-string):
Ad, soyad ve yaş bilgilerini f-string kullanarak şu formatta yazdırın:

`"Merhaba, ben [AD] [SOYAD]. [YAŞ] yaşındayım."`
"""

ad = "Ahmet"
soyad = "Yılmaz"
yas = 25

cumle = f"Merhaba, ben {ad} {soyad}. {yas} yaşındayım."
print(cumle)

"""---
## 4️⃣ Koşullu İfadeler (if / elif / else)
"""

# Örnek
puan = 75

if puan >= 90:
    print("AA")
elif puan >= 80:
    print("BA")
elif puan >= 70:
    print("BB")
elif puan >= 60:
    print("CB")
else:
    print("Başarısız")

"""### 🔸 Soru 7:
Bir sayının pozitif, negatif ya da sıfır olduğunu kontrol eden if-elif-else bloğu yazın.
"""

# Cevabınızı buraya yazın:
sayi = -7
if sayi > 0:
    print("Pozitif")
elif sayi < 0:
    print("Negatif")
else:
    print("Sıfır")

"""### 🔸 Soru 8:
Bir sayının 2'ye ve 3'e tam bölünüp bölünmediğini kontrol edin. 4 farklı durum vardır:
- Hem 2'ye hem 3'e bölünebilir
- Sadece 2'ye bölünebilir
- Sadece 3'e bölünebilir
- Hiçbirine bölünemiyor
"""

# Cevabınızı buraya yazın:
n = 12

n = 12

if n % 2 == 0 and n % 3 == 0:
    print("Hem 2'ye hem 3'e bölünebilir")
elif n % 2 == 0:
    print("Sadece 2'ye bölünebilir")
elif n % 3 == 0:
    print("Sadece 3'e bölünebilir")
else:
    print("Hiçbirine bölünemiyor")

"""---
## 5️⃣ Döngüler (for / while)
"""

# Örnek: for döngüsü
for i in range(1, 6):
    print(f"{i}. adım")

print("---")

# Örnek: while döngüsü
sayac = 0
while sayac < 3:
    print(f"Sayaç: {sayac}")
    sayac += 1

"""### 🔸 Soru 9:
`for` döngüsü ile 1'den 10'a kadar olan sayıların toplamını hesaplayın.
"""

# Cevabınızı buraya yazın:
# Başlangıçta toplamı sıfır olarak tanımlıyoruz
toplam = 0

# range(1, 11) komutu 1'den başlar, 11'e kadar (11 hariç) sayılar üretir
for sayi in range(1, 11):
    toplam += sayi  # Her adımda sayıyı toplam değişkenine ekler

print(f"1'den 10'a kadar olan sayıların toplamı: {toplam}")

"""### 🔸 Soru 10:
`while` döngüsü ile kullanıcının girdiği sayıya (n=5) kadar Fibonacci dizisini yazdırın.

Örnek çıktı: `0, 1, 1, 2, 3`
"""

# Cevabınızı buraya yazın:
# Kullanıcının girdiği sınır değeri
n = 5

# Fibonacci dizisinin ilk iki terimi
a, b = 0, 1
sayac = 0

print(f"{n} terimli Fibonacci dizisi:")

# Sayaç n değerine ulaşana kadar devam eder
while sayac < n:
    # Sayıyı yazdır (virgül ile yan yana gelmesi için end parametresini kullanıyoruz)
    if sayac == n - 1:
        print(a)
    else:
        print(a, end=", ")

    # Yeni sayıları hesapla (a bir sonraki sayı olur, b ise toplamları)
    yeni_sayi = a + b
    a = b
    b = yeni_sayi

    # Sayacı bir artır
    sayac += 1

"""### 🔸 Soru 11 (İç İçe Döngü):
5x5 çarpım tablosunu yazdırın. Her satır şu formatta olsun:

`1x1=1  1x2=2  1x3=3 ...`
"""

# Cevabınızı buraya yazın:

# Dış döngü: 1'den 5'e kadar olan satırlar için
for i in range(1, 6):
    # İç döngü: Her satırdaki 1'den 5'e kadar olan çarpımlar için
    for j in range(1, 6):
        # Çarpımı hesapla ve yan yana yazdır
        # end=" " kullanarak bir sonraki print'in aynı satıra devam etmesini sağlarız
        print(f"{i}x{j}={i*j}", end=" ")

    # Bir satır bittiğinde bir alt satıra geçmek için boş bir print atıyoruz
    print()

"""---
## 6️⃣ Listeler
"""

# Örnek
meyveler = ["elma", "armut", "çilek", "muz"]

print(meyveler[0])          # İlk eleman
print(meyveler[-1])         # Son eleman
print(meyveler[1:3])        # Dilimleme
meyveler.append("kivi")     # Ekleme
meyveler.remove("armut")    # Silme
print(meyveler)

"""### 🔸 Soru 12:
Aşağıdaki listede:
- En büyük ve en küçük elemanı bulun
- Listeyi sıralayın
- 7 sayısının listede kaç kez geçtiğini bulun
- Listeyi tersine çevirin
"""

# Cevabınızı buraya yazın:
sayilar = [3, 7, 1, 9, 7, 4, 7, 2, 8]

# 1. En büyük ve en küçük elemanı bulun
en_buyuk = max(sayilar)
en_kucuk = min(sayilar)
print(f"En büyük sayı: {en_buyuk}")
print(f"En küçük sayı: {en_kucuk}")

# 2. 7 sayısının listede kaç kez geçtiğini bulun
kac_tane_yedi = sayilar.count(7)
print(f"7 sayısı listede {kac_tane_yedi} kez geçiyor.")

# 3. Listeyi sıralayın (Küçükten büyüğe)
sayilar.sort()
print(f"Sıralanmış liste: {sayilar}")

# 4. Listeyi tersine çevirin (Büyükten küçüğe veya mevcut sırayı ters çevirme)
sayilar.reverse()
print(f"Ters çevrilmiş liste: {sayilar}")

"""### 🔸 Soru 13 (List Comprehension):
List comprehension kullanarak:
- 1-20 arasındaki çift sayıların listesini oluşturun
- Bir kelime listesindeki 4'ten uzun kelimeleri filtreleyin
"""

# Cevabınızı buraya yazın:
# 1-20 arası çift sayılar
ciftler = [x for x in range(1, 21) if x % 2 == 0]
print(ciftler)

# 4'ten uzun kelimeler
kelimeler = ["at", "kaplan", "it", "fil", "kedi", "aslan", "köpek"]
uzunlar = [k for k in kelimeler if len(k) > 4]
print(uzunlar)

"""---
## 7️⃣ Sözlükler (Dictionary)
"""

# Örnek
ogrenci = {
    "ad": "Ali",
    "soyad": "Kaya",
    "yas": 20,
    "notlar": [85, 90, 78]
}

print(ogrenci["ad"])
print(ogrenci.get("yas"))
ogrenci["bolum"] = "Bilgisayar Mühendisliği"
print(ogrenci.keys())
print(ogrenci.values())

"""### 🔸 Soru 14:
Bir kitap sözlüğü oluşturun (`baslik`, `yazar`, `yil`, `sayfa_sayisi`) ve:
- Tüm anahtar-değer çiftlerini döngüyle yazdırın
- `fiyat` anahtarı ekleyin
- `yazar` anahtarını silin
"""

# Cevabınızı buraya yazın:
# 1. Kitap sözlüğünü oluşturma
kitap = {
    "baslik": "Nutuk",
    "yazar": "Mustafa Kemal Atatürk",
    "yil": 1927,
    "sayfa_sayisi": 600
}

# 2. fiyat anahtarı ekleme
kitap["fiyat"] = 150

# 3. yazar anahtarını silme
del kitap["yazar"]

# 4. Tüm anahtar-değer çiftlerini döngüyle yazdırma
for anahtar, deger in kitap.items():
    print(f"{anahtar}: {deger}")

"""---
## 8️⃣ Fonksiyonlar
"""

# Örnek
def selamla(isim, nezaket="Merhaba"):
    return f"{nezaket}, {isim}!"

print(selamla("Ayşe"))
print(selamla("Mehmet", "İyi günler"))

"""### 🔸 Soru 15:
Bir sayının asal olup olmadığını kontrol eden `asal_mi(n)` fonksiyonu yazın.
- 1'den 20'ye kadar olan asal sayıları bu fonksiyonu kullanarak yazdırın.
"""

# Cevabınızı buraya yazın:
def asal_mi(n):
    if n < 2:
      return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0: return False
    return True

# 1'den 20'ye kadar olan asalları yazdır
for sayi in range(1, 21):
    if asal_mi(sayi):
        print(sayi, end=" ")

"""### 🔸 Soru 16:
Bir listenin ortalamasını, en büyük ve en küçük elemanını döndüren `liste_istatistik(liste)` fonksiyonu yazın.
Fonksiyon 3 değer döndürsün: `(ortalama, minimum, maksimum)`
"""

# Cevabınızı buraya yazın:
def liste_istatistik(liste):
    ortalama = sum(liste) / len(liste)
    minimum = min(liste)
    maksimum = max(liste)
    return ortalama, minimum, maksimum

test = [4, 8, 15, 16, 23, 42]
ort, mini, maksi = liste_istatistik(test)

print(f"Ortalama: {ort}, Min: {mini}, Max: {maksi}")

"""---
## 9️⃣ Hata Yönetimi (try / except)
"""

# Örnek
try:
    sonuc = 10 / 0
except ZeroDivisionError:
    print("Sıfıra bölme hatası!")
except Exception as e:
    print(f"Beklenmeyen hata: {e}")
finally:
    print("İşlem tamamlandı.")

"""### 🔸 Soru 17:
Kullanıcıdan bir sayı alındığını varsayın (`girdi = "abc"`).
Bu değeri int'e çevirmeye çalışırken `ValueError` hatası oluşabilir.
try-except ile bunu yakalayan ve anlamlı bir mesaj veren kod yazın.
"""

# Cevabınızı buraya yazın:
girdi = "abc"

try:
    # Sayıya çevirme işlemini deniyoruz
    sayi = int(girdi)
    print(f"Girdiğiniz sayı: {sayi}")
except ValueError:
    # Eğer çevirme sırasında hata (ValueError) oluşursa burası çalışır
    print("Hata: Girdiğiniz değer bir sayı değil!")

"""---
## 🔟 Bonus: Kapsamlı Uygulama

### 🔸 Soru 18 (Bütünleştirici):
Bir **not defteri uygulaması** yazın:
- `notlar` adında boş bir liste oluşturun
- `not_ekle(metin)` fonksiyonu: Notu listeye ekler
- `not_listele()` fonksiyonu: Tüm notları numaralandırarak yazdırır
- `not_sil(index)` fonksiyonu: Verilen indexteki notu siler, hatalı index için hata mesajı verir

Fonksiyonları test edin: 3 not ekleyin, listeleyin, ortadakini silin, tekrar listeleyin.
"""

# Cevabınızı buraya yazın:

# 1. Boş notlar listesini oluşturuyoruz
notlar = []

# 2. Not ekleme fonksiyonu
def not_ekle(metin):
    notlar.append(metin)
    print(f"Eklendi: {metin}")

# 3. Notları listeleme fonksiyonu
def not_listele():
    print("\n--- Güncel Notlar ---")
    if not notlar:
        print("Not defteri şu an boş.")
    else:
        for sira, not_metni in enumerate(notlar, start=1):
            print(f"{sira}. {not_metni}")
    print("---------------------\n")

# 4. Not silme fonksiyonu
def not_sil(index):
    try:
        # Kullanıcı 1-tabanlı sayı girdiği için index'ten 1 çıkarıyoruz
        silinen = notlar.pop(index - 1)
        print(f"Silindi: {silinen}")
    except IndexError:
        print(f"Hata: {index} numaralı bir not bulunamadı!")

# --- TEST ADIMLARI ---

# 3 not ekleyelim
not_ekle("Marketten süt al")
not_ekle("Python ödevini tamamla")
not_ekle("Akşam 20:00'de toplantı var")

# Listeleme yapalım
not_listele()

# Ortadaki notu (2. not) silelim
not_sil(2)

# Tekrar listeleyelim
not_listele()
"""notlar = []

def not_ekle(metin):
    pass

def not_listele():
    pass

def not_sil(index):
    pass
"""
# Test kodu:
# not_ekle("Python öğren")
# not_ekle("Alıştırmaları tamamla")
# not_ekle("Proje yap")
# not_listele()
# not_sil(1)
# not_listele()

"""---
## 📊 Özet Çizelgesi

| Konu | Sorular | Tamamlandı mı? |
|------|---------|----------------|
| Değişkenler & Tipler | 1, 2 | evet |
| Operatörler | 3, 4 | evet |
| String İşlemleri | 5, 6 | evet |
| Koşullar | 7, 8 | evet|
| Döngüler | 9, 10, 11 | evet|
| Listeler | 12, 13 | evet |
| Sözlükler | 14 |evet |
| Fonksiyonlar | 15, 16 | evet|
| Hata Yönetimi | 17 | evet |
| Bütünleştirici | 18 |evet
 |

> 💡 **İpucu:** Takıldığınız yerde `help()` fonksiyonunu veya Python dokümantasyonunu kullanın!
"""