# -*- coding: utf-8 -*-
"""python_baslangic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17jn0X98SGI611C01FVoNWrWXjw0mpIs_

# 🐍 Python Başlangıç Defteri
### Adım adım, sade sorularla Python öğrenin!
---

## 1️⃣ print() Fonksiyonu
"""

# Örnek
print("Merhaba!")
print(42)
print("Sonuç:", 10 + 5)

"""### ✏️ Soru 1: Ekrana kendi adınızı yazdırın."""

# Buraya yazın:

"""### ✏️ Soru 2: `print()` kullanarak 3 farklı satırda şunları yazdırın:
- Adınız
- Yaşınız
- Şehriniz
"""

# Buraya yazın:

"""---
## 2️⃣ Değişkenler
"""

# Örnek
isim = "Ahmet"
yas = 20
print(isim)
print(yas)

"""### ✏️ Soru 3: `sehir` adında bir değişken oluşturun ve değerini yazdırın."""

# Buraya yazın:

"""### ✏️ Soru 4: `sayi1 = 8` ve `sayi2 = 3` değişkenlerini tanımlayın. Toplamlarını `toplam` değişkenine atayın ve yazdırın."""

# Buraya yazın:
sayi1 = 8
sayi2 = 3

"""---
## 3️⃣ Veri Tipleri
"""

# Örnek
print(type("merhaba"))   # str
print(type(10))          # int
print(type(3.14))        # float
print(type(True))        # bool

"""### ✏️ Soru 5: Aşağıdaki 4 değişkenin tipini `type()` ile yazdırın."""

a = "python"
b = 100
c = 9.99
d = False

# Buraya yazın:

"""### ✏️ Soru 6: `"25"` metnini sayıya (`int`), `7` sayısını metne (`str`) çevirin ve yazdırın."""

# Buraya yazın:
metin = "25"
sayi = 7

"""---
## 4️⃣ Aritmetik İşlemler
"""

# Örnek
print(10 + 3)   # 13
print(10 - 3)   # 7
print(10 * 3)   # 30
print(10 / 3)   # 3.333...
print(10 // 3)  # 3  (tam bölme)
print(10 % 3)   # 1  (kalan)
print(2 ** 4)   # 16 (üs)

"""### ✏️ Soru 7: `a = 15`, `b = 4` için toplama, çıkarma, çarpma ve bölme işlemlerini yapın."""

a = 15
b = 4
# Buraya yazın:

"""### ✏️ Soru 8: 17'yi 5'e böldüğünüzde kalan nedir? `%` operatörü ile bulun."""

# Buraya yazın:

"""---
## 5️⃣ String (Metin) İşlemleri
"""

# Örnek
metin = "merhaba"
print(metin.upper())       # MERHABA
print(metin.lower())       # merhaba
print(len(metin))          # 7
print(metin[0])            # m  (ilk harf)
print(metin[-1])           # a  (son harf)

"""### ✏️ Soru 9: `isim = "python"` değişkeni için:
- Büyük harfle yazdırın
- Kaç harf olduğunu yazdırın
- İlk harfini yazdırın
"""

isim = "python"
# Buraya yazın:

"""### ✏️ Soru 10: İki metni birleştirin. `ad = "Ali"` ve `soyad = "Yılmaz"` → `"Ali Yılmaz"` yazdırın."""

ad = "Ali"
soyad = "Yılmaz"
# Buraya yazın:

"""### ✏️ Soru 11: f-string kullanarak şu çıktıyı üretin: `"Merhaba, ben Ali. 25 yaşındayım."`"""

ad = "Ali"
yas = 25
# Buraya yazın:

"""---
## 6️⃣ Koşullar (if / else)
"""

# Örnek
sayi = 10
if sayi > 0:
    print("Pozitif")
else:
    print("Sıfır veya negatif")

"""### ✏️ Soru 12: `yas = 16` değişkeni için; 18'den büyükse `"Ehliyet alabilir"`, değilse `"Ehliyet alamaz"` yazdırın."""

yas = 16
# Buraya yazın:

"""### ✏️ Soru 13: `sayi = 7` değişkeni için; çift mi tek mi olduğunu yazdırın. (`%` operatörü kullanın)"""

sayi = 7
# Buraya yazın:

"""### ✏️ Soru 14: `puan = 65` için not harfini yazdırın:
- 90 ve üstü → `"A"`
- 75 ve üstü → `"B"`
- 60 ve üstü → `"C"`
- 60 altı → `"F"`
"""

puan = 65
# Buraya yazın:

"""---
## 7️⃣ for Döngüsü
"""

# Örnek
for i in range(5):
    print(i)   # 0, 1, 2, 3, 4

for i in range(1, 6):
    print(i)   # 1, 2, 3, 4, 5

"""### ✏️ Soru 15: 1'den 10'a kadar olan sayıları yazdırın."""

# Buraya yazın:

"""### ✏️ Soru 16: 1'den 10'a kadar olan sayıların toplamını hesaplayın."""

# Buraya yazın:
toplam = 0

"""### ✏️ Soru 17: Aşağıdaki listedeki her meyveyi ayrı satırda yazdırın."""

meyveler = ["elma", "armut", "muz", "çilek"]
# Buraya yazın:

"""---
## 8️⃣ Listeler
"""

# Örnek
liste = [10, 20, 30, 40, 50]
print(liste[0])       # 10 (ilk eleman)
print(liste[-1])      # 50 (son eleman)
print(len(liste))     # 5
liste.append(60)      # sona ekle
print(liste)

"""### ✏️ Soru 18: Aşağıdaki listede:
- İlk elemanı yazdırın
- Son elemanı yazdırın
- Listenin uzunluğunu yazdırın
"""

renkler = ["kırmızı", "mavi", "yeşil", "sarı", "beyaz"]
# Buraya yazın:

"""### ✏️ Soru 19: Listeye `"turuncu"` ekleyin, sonra `"mavi"` yi silin ve listeyi yazdırın."""

renkler = ["kırmızı", "mavi", "yeşil", "sarı"]
# Buraya yazın:

"""### ✏️ Soru 20: Sayılar listesindeki en büyük, en küçük değeri ve toplamı yazdırın."""

sayilar = [5, 12, 3, 8, 19, 1, 7]
# İpucu: max(), min(), sum() fonksiyonlarını kullanın
# Buraya yazın:

"""---
## 9️⃣ Fonksiyonlar
"""

# Örnek
def topla(a, b):
    return a + b

sonuc = topla(3, 5)
print(sonuc)  # 8

"""### ✏️ Soru 21: İki sayıyı çarpan `carp(a, b)` fonksiyonu yazın ve `carp(4, 6)` ile test edin."""

# Buraya yazın:

"""### ✏️ Soru 22: Bir isim alıp `"Merhaba, [isim]!"` şeklinde yazdıran `selamla(isim)` fonksiyonu yazın."""

# Buraya yazın:

"""### ✏️ Soru 23: Bir sayının çift mi tek mi olduğunu döndüren `cift_mi(sayi)` fonksiyonu yazın. `True` veya `False` dönsün."""

# Buraya yazın:
def cift_mi(sayi):
    pass

print(cift_mi(4))   # True
print(cift_mi(7))   # False

"""---
## 🔟 Hepsini Birleştir!

### ✏️ Soru 24:
Bir alışveriş sepeti uygulaması yapın:
- `sepet = []` listesi oluşturun
- 3 ürün ekleyin (`.append()`)
- `for` döngüsü ile ürünleri numaralı yazdırın
- Kaç ürün olduğunu yazdırın
"""

# Buraya yazın:
sepet = []

"""### ✏️ Soru 25:
Bir listede verilen notların ortalamasını hesaplayan `ortalama(notlar)` fonksiyonu yazın.
- `sum()` ve `len()` kullanabilirsiniz
- `[70, 85, 90, 60, 75]` listesiyle test edin
"""

# Buraya yazın:
def ortalama(notlar):
    pass

test_notlari = [70, 85, 90, 60, 75]
# print(ortalama(test_notlari))  # 76.0 olmalı

"""---
## 📊 İlerleme Tablosu

| Konu | Sorular | Bitti mi? |
|------|---------|----------|
| print() | 1, 2 | ☐ |
| Değişkenler | 3, 4 | ☐ |
| Veri Tipleri | 5, 6 | ☐ |
| Aritmetik | 7, 8 | ☐ |
| String | 9, 10, 11 | ☐ |
| if / else | 12, 13, 14 | ☐ |
| for Döngüsü | 15, 16, 17 | ☐ |
| Listeler | 18, 19, 20 | ☐ |
| Fonksiyonlar | 21, 22, 23 | ☐ |
| Birleştirici | 24, 25 | ☐ |

> 💡 Hata almaktan korkmayın — hatalar öğrenmenin en iyi yoludur!
"""